/* 1 - housings */
CREATE TABLE IF NOT EXISTS housings (
id_housing INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
address VARCHAR
);
SELECT * FROM housings;

/* 2 - faculties */
CREATE TABLE IF NOT EXISTS faculties (
id_faculty INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
id_housing INT,
FOREIGN KEY (id_housing) REFERENCES housings (id_housing)
);
SELECT * FROM faculties;

/* 3 - teachers */
CREATE TABLE IF NOT EXISTS teachers (
id_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
post VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM teachers;

/* 4 - students */
CREATE TABLE IF NOT EXISTS students (
id_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM students;

/* 5 subjects */
CREATE TABLE IF NOT EXISTS subjects (
id_subject INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
learning_hours NUMERIC,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM subjects;

/* 6 - marks */
CREATE TABLE IF NOT EXISTS marks (
id_mark INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
mark_type VARCHAR,
id_subject INT,
id_student INT,
mark NUMERIC,
id_teacher INT,
date_m DATE,
id_schedule INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher),
FOREIGN KEY (id_schedule) REFERENCES schedules(id_schedule)
);
SELECT * FROM marks;

/*7 - schedules */
CREATE TABLE IF NOT EXISTS schedules (
    id_schedule INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_faculty INT,
    id_subject INT,
    week_day VARCHAR(20),
    time TIME,
    lesson_type VARCHAR(50),
    id_teacher INT,
    FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty),
    FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
    FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM schedules;

/*-- Добавление связи с таблицей marks
ALTER TABLE marks ADD COLUMN id_schedule INT;
ALTER TABLE marks ADD FOREIGN KEY (id_schedule) REFERENCES schedules (id_schedule); */

/* 8 - sub_teachers */
CREATE TABLE IF NOT EXISTS sub_teachers (
id_sub_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_teacher INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM sub_teachers;

/* 9 - sub_students */
CREATE TABLE IF NOT EXISTS sub_students (
id_sub_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_student INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student)
);
SELECT * FROM sub_students;

-----Добавляем корпуса------
INSERT INTO housings (title, address) VALUES 
('Корпус Радуги', 'ул. Веселая, 10'),
('Арткорпус', 'пр. Художественный, 5'),
('Звуковой Центр', 'ул. Музыкальная, 21'),
('Креативная Башня', 'бул. Архитекторов, 33'),
('Фантазийный Холл', 'пер. Воображения, 7');

SELECT * FROM housings;


----Добавляем направления-----
INSERT INTO faculties (title, id_housing) VALUES 
('Архитектура', 4),
('Изобразительное искусство', 2),
('Музыкальное искусство', 3),
('Цирковое искусство', 5),
('Хореография', 5),
('Кино и мультфильмы', 1),
('Дизайн одежды', 2),
('Театральное искусство', 1),
('Геймдизайн', 4),
('Фантастическая инженерия', 3);

SELECT * FROM faculties;

--ADD teachers---
-- Архитектура (id_faculty=1)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Иванов Петр Сергеевич', '7 (912) 345-67-89', 'Профессор', 1),
('Смирнова Анна Владимировна', 'architect.smirnova@mail.ru', 'Доцент', 1);

-- Изобразительное искусство (id_faculty=2)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Кузнецова Елена Дмитриевна', '7 (923) 456-78-90', 'Профессор', 2),
('Петров Алексей Иванович', 'art.petrov@gmail.com', 'Старший преподаватель', 2),
('Васильева Ольга Николаевна', '7 (934) 567-89-01', 'Доцент', 2);

-- Музыкальное искусство (id_faculty=3)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Соколов Дмитрий Михайлович', 'music.sokolov@yandex.ru', 'Профессор', 3),
('Николаева Татьяна Викторовна', '7 (945) 678-90-12', 'Старший преподаватель', 3);

-- Цирковое искусство (id_faculty=4)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Попов Сергей Александрович', '7 (956) 789-01-23', 'Старший преподаватель', 4),
('Федорова Марина Игоревна', 'circus.fedorova@mail.ru', 'Ассистент', 4);

-- Хореография (id_faculty=5)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Лебедева Анастасия Олеговна', '7 (967) 890-12-34', 'Доцент', 5),
('Козлов Артем Викторович', 'dance.kozlov@gmail.com', 'Старший преподаватель', 5);

-- Кино и мультфильмы (id_faculty=6)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Морозов Игорь Станиславович', 'film.morozov@yandex.ru', 'Профессор', 6),
('Павлова Виктория Сергеевна', '7 (978) 901-23-45', 'Ассистент', 6),
('Сидоров Максим Леонидович', '7 (911) 222-33-44', 'Завуч', 6);

-- Дизайн одежды (id_faculty=7)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Семенова Людмила Анатольевна', 'fashion.semenova@mail.ru', 'Профессор', 7),
('Григорьев Павел Олегович', '7 (989) 012-34-56', 'Доцент', 7);

-- Театральное искусство (id_faculty=8)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Волкова Екатерина Денисовна', 'theatre.volkova@gmail.com', 'Доцент', 8),
('Белов Александр Петрович', '7 (990) 123-45-67', 'Старший преподаватель', 8);

-- Геймдизайн (id_faculty=9)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Тихонов Андрей Владимирович', 'game.tikhonov@yandex.ru', 'Профессор', 9),
('Крылова Юлия Михайловна', '7 (901) 234-56-78', 'Ассистент', 9);

-- Фантастическая инженерия (id_faculty=10)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Орлов Денис Игоревич', 'fantasy.engineer@mail.ru', 'Профессор', 10),
('Зайцева Наталья Валерьевна', '7 (912) 345-67-89', 'Доцент', 10),
('Михайлов Сергей Васильевич', '7 (903) 456-78-90', 'Завуч', 10);



--Добавить Студентов---
-- Архитектура (id_faculty=1)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Соколов Артем Игоревич', '7 (901) 234-56-78', 1),
('Кудабаева Эвита', 'arch.student@mail.ru', 1);

-- Изобразительное искусство (id_faculty=2)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Петрова Виктория Андреевна', 'art.lover@gmail.com', 2),
('Жуков Денис Олегович', '7 (912) 345-67-89', 2);

-- Музыкальное искусство (id_faculty=3)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Никитин Александр Дмитриевич', 'music.prodigy@yandex.ru', 3);

-- Цирковое искусство (id_faculty=4)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Алексеева Марина Валерьевна', '7 (923) 456-78-90', 4);

-- Хореография (id_faculty=5)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Громов Илья Петрович', 'dance.gromov@mail.ru', 5),
('Орлова Дарья Кирилловна', '7 (934) 567-89-01', 5);

-- Кино и мультфильмы (id_faculty=6)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Беляев Максим Андреевич', 'film.director@gmail.com', 6);

-- Дизайн одежды (id_faculty=7)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Степанова Алина Михайловна', 'fashion.design@yandex.ru', 7),
('Фролов Иван Сергеевич', '7 (945) 678-90-12', 7);

-- Театральное искусство (id_faculty=8)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Данилова Ксения Викторовна', 'theatre.star@mail.ru', 8);

-- Геймдизайн (id_faculty=9)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Тимофеев Денис Олегович', 'game.dev@gmail.com', 9),
('Савельева Анна Дмитриевна', '7 (956) 789-01-23', 9);

-- Фантастическая инженерия (id_faculty=10)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Кузьмин Павел Андреевич', 'future.engineer@yandex.ru', 10);

