/* ----- LAB 3 ------ */
/*---- 3 laba ArtSchool ---- */

-- 2. Create a simple view and query data
CREATE VIEW v_teacher_subjects AS
SELECT t.fio, s.title
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject;

SELECT * FROM v_teacher_subjects;

-- 3. Verify data with a direct query CHECK +
SELECT t.fio, s.title
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject;


-- 4. Alter the view to add column aliases
ALTER VIEW v_teacher_subjects RENAME COLUMN fio TO teacher_name;
ALTER VIEW v_teacher_subjects RENAME COLUMN title TO subject_name;

SELECT * FROM v_teacher_subjects;

-- 5. Modify the view's query (CREATE OR REPLACE)
CREATE OR REPLACE VIEW v_teacher_subjects AS
SELECT t.fio AS teacher_name, s.title AS subject_name , t.post AS teacher_post
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject
WHERE t.post = 'Доцент';  -- Added a condition

SELECT * FROM v_teacher_subjects;


-- 6. Insert data through the view (generally not recommended for complex views)
-- Demonstrate with a simpler view:
CREATE VIEW v_student_faculty AS
SELECT id_student, fio, id_faculty
FROM students;


INSERT INTO v_student_faculty(id_student, fio, id_faculty)
VALUES (25, 'New Student', 3); --Insert careful, id_student can be auto-generated

SELECT * FROM students WHERE id_student=25; -- Check if data is inserted
SELECT * FROM students;

-- 7. Create a view with WITH CHECK OPTION
CREATE OR REPLACE VIEW v_high_marks AS
SELECT id_mark, mark_type, id_subject, id_student, mark
FROM marks
WHERE mark >= 4
WITH CHECK OPTION;


SELECT * FROM v_high_marks;

-- Attempt to insert data that violates the condition (should fail)
INSERT INTO v_high_marks(id_mark, mark_type, id_subject, id_student, mark) 
VALUES (27, 'Экзамен', 1, 1, 3); -- This will raise an error because mark < 4


-- 8. Drop a view
DROP VIEW v_teacher_subjects;



-- 9. Create a view from two tables in UI PGADMIN 
/* CREATE VIEW v_student_marks AS
SELECT s.fio AS student_name, m.mark, sb.title AS subject_title
FROM students s
JOIN marks m ON s.id_student = m.id_student
JOIN subjects sb ON m.id_subject = sb.id_subject;
*/
SELECT * FROM v_student_marks;


-- 10-11
CREATE ROLE Test_creator WITH NOLOGIN CREATEDB CREATEROLE;
CREATE USER user_1 WITH LOGIN NOCREATEDB NOCREATEROLE PASSWORD '123';

DROP ROLE Test_creator;
DROP ROLE user_1;

CREATE DATABASE test_user_1_db;
DROP DATABASE IF EXISTS test_user1_db;
GRANT Test_creator TO user_1;


REVOKE Test_creator FROM user_1;

-- user_2 without rights
SET ROLE postgres;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC FROM user_2;
SET ROLE user_2;
SELECT * FROM students;

-- user_2 with rights
SET ROLE postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO user_2;
SET ROLE user_2;
SELECT * FROM students;

-- user_2 without requests
SET ROLE postgres;
REVOKE SELECT ON ALL TABLES IN SCHEMA PUBLIC FROM user_2;
SET ROLE user_2;
SELECT * FROM students;
/*CREATE TABLE table_test(
id_test INT,
);
*/
-- user_2 with requests
SET ROLE postgres;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO user_2;
SET ROLE user_2;
SELECT * FROM students;

-- user_2 without insert table
SET ROLE postgres;
REVOKE INSERT ON ALL TABLES IN SCHEMA PUBLIC FROM user_2;
SET ROLE user_2;
INSERT INTO housings(id_housing, title, address) VALUES
(default, 'Wonderland', 'Nowhere');
SELECT * FROM housings;


/*
CREATE ROLE role_notable WITH NOLOGIN;
CREATE ROLE role_table WITH NOLOGIN;

DROP ROLE role_notable;
DROP ROLE role_table;
CREATE USER user2 WITH LOGIN PASSWORD 'password';
DROP USER user2;
GRANT role_notable TO user2;
-- (As user2 - should fail to create a table)
-- CREATE TABLE test_table (id INT); 

CREATE TABLE test_table (
	id_table INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	test_atribute VARCHAR
);

REVOKE role_table FROM user2;
GRANT role_table TO user2;  -- Grant create privileges below
GRANT CREATE ON DATABASE Sales TO role_table; 
REVOKE role_table FROM user3;

-- or for *all* databases
-- ALTER ROLE role_table CREATEDB;
-- (As user2 - should succeed now after reconnecting or refreshing)
-- CREATE TABLE test_table (id INT); 
CREATE USER user3 WITH LOGIN PASSWORD '111';
GRANT role_table TO user3;
GRANT ALL PRIVILEGES ON TABLE housings TO user3;
-- (As user3 - test permissions - should have all privileges)
INSERT INTO housings(id_housing, title, address) VALUES
(11, 'Random','Nowhere');
SELECT * FROM housings;
REVOKE INSERT ON TABLE housings FROM user3;
REVOKE ALL PRIVILEGES ON TABLE students FROM user3;
REVOKE ALL PRIVILEGES ON TABLE housings FROM user3;
-- (As user3 - should no longer be able to insert)

-- Cleanup (optional):
-- DROP ROLE test_creator;
-- DROP USER user1;
-- DROP USER user2;
-- DROP USER user3;
-- DROP VIEW v_student_faculty;
-- DROP VIEW v_high_marks;
-- DROP VIEW v_student_marks;
*/