/* --------------------------------------------------------- */

/* 1 - housings */
CREATE TABLE IF NOT EXISTS housings (
id_housing INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
address VARCHAR
);
SELECT * FROM housings;

/* 2 - faculties */
CREATE TABLE IF NOT EXISTS faculties (
id_faculty INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
id_housing INT,
FOREIGN KEY (id_housing) REFERENCES housings (id_housing)
);
SELECT * FROM faculties;

/* 3 - teachers */
CREATE TABLE IF NOT EXISTS teachers (
id_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
post VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM teachers;

/* 4 - students */
CREATE TABLE IF NOT EXISTS students (
id_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM students;

/* 5 subjects */
CREATE TABLE IF NOT EXISTS subjects (
id_subject INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
learning_hours NUMERIC,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM subjects;

/* 6 - marks */
CREATE TABLE IF NOT EXISTS marks (
id_mark INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
mark_type VARCHAR,
id_subject INT,
id_student INT,
mark NUMERIC,
id_teacher INT,
date_m DATE,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM marks;

/* 7 - sub_teachers */
CREATE TABLE IF NOT EXISTS sub_teachers (
id_sub_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_teacher INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM sub_teachers;

/* 8 - sub_students */
CREATE TABLE IF NOT EXISTS sub_students (
id_sub_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_student INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student)
);
SELECT * FROM sub_students;

/* --------------------------------------------------------- */


/* DROP TABLE IF EXISTS sub_students; */
INSERT INTO housings (id_housing, title, address) VALUES
(1, 'ИЗО Традиционное', 'Улица Ван Гога, д.1, к.1'),
(2, 'Архитектура', 'Улица Щусева, д.2, к.2'),
(3, '2D цифровое', 'Улица Мир, д.3, к.3'),
(4, '3D цифровое', 'Улица Глобус, д.4, к.4'),
(5, 'Музыка: традиционная', 'Улица Росс, д.5, к.5'),
(6, 'Музыка: электронная', 'Улица Стан, д.6, к.6'),
(7, 'Литература: классическая', 'Улица Пушкинская, д.7, к.7'),
(8, 'Литература: цифровая', 'Улица Мята, д.8, к.8'),
(9, 'Танцы: классические', 'Улица Вальсова, д.9, к.9'),
(10, 'Танцы: современные', 'Улица Хопинская, д.10, к.10');

INSERT INTO faculties (id_faculty, title, id_housing) VALUES
(1, 'ИЗО Традиционное', 1),
(2, 'Архитектура', 2),
(3, '2D цифровое', 3),
(4, '3D цифровое', 4),
(5, 'Музыка: традиционная', 5),
(6, 'Музыка: электронная', 6),
(7, 'Литература: классическая', 7),
(8, 'Литература: цифровая', 8),
(9, 'Танцы: классические', 9),
(10, 'Танцы: современные', 10);

INSERT INTO teachers(id_teacher, fio, contacts, post, id_faculty) VALUES
(1,'Архипова Алиса Степановна','7(495) 181-55-00','Старший преподаватель',1),
(2,'Чижова Полина Егоровна','7(495) 994-96-19','Преподаватель',1),
(3,'Иванова Дарья Романовна','7(495) 449-59-77','Старший преподаватель',10),
(4,'Воронов Матвей Константинович','7(495) 244-24-44','Преподаватель',10),
(5,'Власов Борис Григорьевич','7(495) 735-93-42','Преподаватель',3),
(6,'Черепанов Вячеслав Владиславович','7(495) 139-80-19','Преподаватель',6),
(7,'Владимирова Мия Ильинична','7(495) 548-09-74','Завуч',6),
(8,'Еремин Марсель Антонович','7(495) 229-64-58','Ассистент',8),
(9,'Булгаков Егор Маркович','7(495) 585-68-57','Старший преподаватель',8),
(10,'Пономарева Маргарита Максимовна','7(495) 633-38-60','Доцент',8),
(11,'Степанова Александра Романовна','7(495) 287-77-02','Ассистент',9),
(12,'Логинов Александр Матвеевич','7(495) 133-61-34','Профессор',9),
(13,'Макаров Дмитрий Артемьевич','7(495) 156-85-71','Старший преподаватель',3),
(14,'Петрова Александра Михайловна','7(495) 803-83-04','Старший преподаватель',4),
(15,'Новиков Семён Григорьевич','7(495) 825-16-09','Профессор',7),
(16,'Павлов Дмитрий Егорович','7(495) 498-20-63','Доцент',5),
(17,'Козина Агата Фёдоровна','7(495) 597-63-81','Доцент',3),
(18,'Панин Лев Кириллович','7(495) 818-81-67','Ассистент',1),
(19,'Фомин Артём Андреевич','7(495) 942-57-57','Доцент',9),
(20,'Бирюкова Есения Григорьевна','7(495) 703-51-28','Старший преподаватель',5),
(21,'Козлова Маргарита Матвеевна','7(495) 264-93-60','Профессор',5),
(22,'Максимов Михаил Львович','7(495) 947-52-65','Доцент',4),
(23,'Мартынов Денис Романович','7(495) 997-18-95','Ассистент',2),
(24,'Гончарова Арина Ильинична','7(495) 686-38-10','Доцент',2);

INSERT INTO students(id_student, fio, contacts, id_faculty) VALUES
(1, 'Кудабаева Эвита', '7(987) 578-86-54', 1),
(2, 'Пупкин Вася Васильевич', '7(466) 865-78-85', 2),
(3, 'Лупкин Лена Леонидович', '7(987) 655-67-88', 3),
(4, 'Красочный Денис Васильевич', '7(987) 667-89-76', 4),
(5, 'Красивая Юлия Кирилловна', '7(495) 533-26-79', 5),
(6, 'Лучшая Марина Андреевна', '7(495) 157-00-44', 6),
(7, 'Умная Анастасия Борисовна', '7(495) 909-95-07', 7),
(8, 'Величайший Сергей Антонович', '7(495) 151-85-06', 8),
(9, 'Изумительнейший Акакий Акакиевич', '7(495) 867-89-23', 9),
(10, 'Клёвый Никита Сергеевич', '7(495) 943-38-29', 10),
(11, 'Махаббатов Михаил Эрсенович', '7(495) 783-29-88', 9),
(12, 'Суетливый Бахтияр', '7(495) 554-79-06', 8),
(13, 'Побеждаева Мадина', '7(495) 004-39-67', 8),
(14, 'Хафиан Парванна', '7(495) 960-85-95', 6),
(15, 'М''Бату Накия', '7(495) 888-95-96', 6),
(16, 'Губайдулина Софья Игнатовна', '7(495) 012-78-43', 3),
(17, 'Шамиев Вазген Амирарович', '7(495) 515-47-98', 3),
(18, 'Абашев Максим Александрович', '7(495) 662-62-52', 7),
(19, 'Алашему Гела', '7(495) 910-35-38', 7),
(20, 'Волощук Александр', '7(495) 987-86-56', 7),
(21, 'Трундаев Дмитрий', '7(495) 592-01-38', 5),
(22, 'Алпхи Мемет Меметрович', '7(495) 411-89-02', 1),
(23, 'Хазаров Гасан Гасанович', '7(495) 708-37-16', 1),
(24, 'Незаеальная Анна Михайловна', '7(495) 432-71-72', 4);

INSERT INTO subjects(id_subject, title, learning_hours, id_faculty) VALUES
(1, 'МХК База', 120, 1),
(2, 'МХК продвинутая', 134, 1),
(3, 'Основы Архитектуры', 111, 2),
(4, 'Физика', 156, 2),
(5, 'Сопромат для маленьких', 127, 2),
(6, 'Практическая Геометрия', 124, 2),
(7, 'Черчение', 123, 2),
(8, 'Черчение ИЗО', 200, 1),
(9, 'Композиция', 129, 1),
(10, 'Основы цифрового творчества', 152, 3),
(11, 'Теория композиции', 100, 3),
(12, 'Практическое изображение', 192, 3),
(13, 'Основы цифрового пространства', 182, 4),
(14, 'Скулптинг', 231, 4),
(15, 'Основы схемо-изображения', 271, 4),
(16, 'МИМ', 121, 5),
(17, 'Нотная грамота и теория музыки', 181, 5),
(18, 'Прикладное музицирование', 122, 5),
(19, 'МИМ и ЭМ', 125, 6),
(20, 'Основы музыкальной теории и цифровых инструментов', 136, 6),
(21, 'Прикладное создание сэмплов', 137, 6),
(22, 'Мировая литература', 141, 7),
(23, 'Основы художественного описания', 151, 7),
(24, 'Прикладное сочинение', 172, 7);

INSERT INTO marks(id_mark, mark_type, id_subject, id_student, mark, id_teacher, date_m) VALUES
(1, 'Зачет', 1, 1, 5, 20, '2024-09-20'),
(2, 'Зачет', 1, 1, 4, 18, '2024-10-01'),
(3, 'Зачет', 5, 2, 3, 24, '2024-10-10'),
(4, 'Экзамен', 14, 3, 5, 19, '2024-10-02'),
(5, 'Зачет', 12, 4, 2, 5, '2024-10-02'),
(6, 'Экзамен', 24, 5, 2, 4, '2024-10-02'),
(7, 'Зачет', 3, 6, 5, 22, '2024-10-17'),
(8, 'Зачет', 10, 7, 3, 17, '2024-10-22'),
(9, 'Экзамен', 13, 8, 2, 22, '2024-10-09'),
(10, 'Зачет', 21, 9, 5, 7, '2024-10-17'),
(11, 'Зачет', 2, 10, 5, 2, '2024-10-25'),
(12, 'Зачет', 22, 11, 4, 15, '2024-10-02'),
(13, 'Экзамен', 15, 12, 2, 14, '2024-10-26'),
(15, 'Экзамен', 7, 13, 3, 23, '2024-10-02'),
(16, 'Зачет', 11, 14, 3, 13, '2024-11-13'),
(17, 'Экзамен', 4, 15, 5, 24, '2024-11-03'),
(18, 'Экзамен', 20, 16, 5, 6, '2024-11-08'),
(19, 'Зачет', 18, 17, 4, 16, '2024-10-24'),
(20, 'Зачет', 8, 18, 2, 1, '2024-10-24'),
(21, 'Экзамен', 19, 19, 3, 9, '2024-10-30'),
(22, 'Экзамен', 17, 20, 2, 20, '2024-10-04'),
(23, 'Экзамен', 9, 21, 4, 18, '2024-10-05'),
(24, 'Зачет', 23, 22, 4, 15, '2024-10-24'),
(25, 'Зачет', 13, 23, 5, 22, '2024-10-19'),
(26, 'Экзамен', 16, 24, 3, 3, '2024-10-31');

INSERT INTO sub_teachers(id_sub_teacher, id_subject, id_teacher) VALUES
(1, 1, 1),
(2, 2, 2),
(3, 3, 3),
(4, 12, 4),
(5, 10, 5),
(6, 19, 6),
(7, 21, 7),
(8, 23, 8),
(9, 16, 9),
(10, 19, 10),
(11, 8, 11),
(12, 22, 12),
(13, 11, 13),
(14, 13, 14),
(15, 22, 15),
(16, 16, 16),
(17, 12, 17),
(18, 3, 18),
(19, 14, 19),
(20, 17, 20),
(21, 18, 21),
(22, 4, 22),
(23, 20, 23),
(24, 5, 24);

INSERT INTO sub_students(id_sub_student, id_subject, id_student) VALUES
(1, 1, 17),
(2, 2, 11),
(3, 3, 4),
(4, 4, 5),
(5, 5, 8),
(6, 6, 1),
(7, 7, 24),
(8, 8, 2),
(9, 9, 6),
(10, 10, 23),
(11, 11, 12),
(12, 12, 3),
(13, 13, 18),
(14, 14, 20),
(15, 15, 7),
(16, 16, 9),
(17, 17, 13),
(18, 18, 19),
(19, 19, 15),
(20, 20, 10),
(21, 21, 21),
(22, 22, 23),
(23, 23, 16),
(24, 24, 4);

/* ----- LAB 3 ------ */
/*---- 3 laba ArtSchool ---- */

-- 2. Create a simple view and query data
CREATE VIEW v_teacher_subjects AS
SELECT t.fio, s.title
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject;

SELECT * FROM v_teacher_subjects;

-- 3. Verify data with a direct query CHECK +
SELECT t.fio, s.title
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject;


-- 4. Alter the view to add column aliases
ALTER VIEW v_teacher_subjects RENAME COLUMN fio TO teacher_name;
ALTER VIEW v_teacher_subjects RENAME COLUMN title TO subject_name;

SELECT * FROM v_teacher_subjects;

-- 5. Modify the view's query (CREATE OR REPLACE)
CREATE OR REPLACE VIEW v_teacher_subjects AS
SELECT t.fio AS teacher_name, s.title AS subject_name , t.post AS teacher_post
FROM teachers t
JOIN sub_teachers st ON t.id_teacher = st.id_teacher
JOIN subjects s ON st.id_subject = s.id_subject
WHERE t.post = 'Доцент';  -- Added a condition

SELECT * FROM v_teacher_subjects;


-- 6. Insert data through the view (generally not recommended for complex views)
-- Demonstrate with a simpler view:
CREATE VIEW v_student_faculty AS
SELECT id_student, fio, id_faculty
FROM students;


INSERT INTO v_student_faculty(id_student, fio, id_faculty)
VALUES (25, 'New Student', 3); --Insert careful, id_student can be auto-generated

SELECT * FROM students WHERE id_student=25; -- Check if data is inserted
SELECT * FROM students;

-- 7. Create a view with WITH CHECK OPTION
CREATE OR REPLACE VIEW v_high_marks AS
SELECT id_mark, mark_type, id_subject, id_student, mark
FROM marks
WHERE mark >= 4
WITH CHECK OPTION;


SELECT * FROM v_high_marks;

-- Attempt to insert data that violates the condition (should fail)
INSERT INTO v_high_marks(id_mark, mark_type, id_subject, id_student, mark) 
VALUES (27, 'Экзамен', 1, 1, 3); -- This will raise an error because mark < 4


-- 8. Drop a view
DROP VIEW v_teacher_subjects;



-- 9. Create a view from two tables in UI PGADMIN 
/* CREATE VIEW v_student_marks AS
SELECT s.fio AS student_name, m.mark, sb.title AS subject_title
FROM students s
JOIN marks m ON s.id_student = m.id_student
JOIN subjects sb ON m.id_subject = sb.id_subject;
*/
SELECT * FROM v_student_marks;


-- 10-16. Role and permission management (PostgreSQL specific commands)
CREATE ROLE test_creator WITH NOLOGIN CREATEDB CREATEROLE;
CREATE USER user1 WITH LOGIN NOCREATEDB NOCREATEROLE PASSWORD '123';

DROP ROLE test_creator;
DROP ROLE user1;
-- Check that user1 cannot create a database (in a new connection as user1)
-- CREATE DATABASE test_user1_db;  -- This should fail for user1
CREATE DATABASE test_user1_db;
DROP DATABASE IF EXISTS test_user1_db;
GRANT test_creator TO user1;
REVOKE user1 FROM test_creator;
-- Reconnect as user1 (or refresh privileges in the current session)
-- CREATE DATABASE test_user1_db; -- This should now succeed

CREATE ROLE role_notable WITH NOLOGIN;
CREATE ROLE role_table WITH NOLOGIN;

DROP ROLE role_notable;
DROP ROLE role_table;
CREATE USER user2 WITH LOGIN PASSWORD 'password';
DROP USER user2;
GRANT role_notable TO user2;
-- (As user2 - should fail to create a table)
-- CREATE TABLE test_table (id INT); 

CREATE TABLE test_table (
	id_table INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	test_atribute VARCHAR
);

REVOKE role_table FROM user2;
GRANT role_table TO user2;  -- Grant create privileges below
GRANT CREATE ON DATABASE Sales TO role_table; 
REVOKE role_table FROM user3;

-- or for *all* databases
-- ALTER ROLE role_table CREATEDB;
-- (As user2 - should succeed now after reconnecting or refreshing)
-- CREATE TABLE test_table (id INT); 
CREATE USER user3 WITH LOGIN PASSWORD '111';
GRANT role_table TO user3;
GRANT ALL PRIVILEGES ON TABLE housings TO user3;
-- (As user3 - test permissions - should have all privileges)
INSERT INTO housings(id_housing, title, address) VALUES
(11, 'Random','Nowhere');
SELECT * FROM housings;
REVOKE INSERT ON TABLE housings FROM user3;
REVOKE ALL PRIVILEGES ON TABLE students FROM user3;
REVOKE ALL PRIVILEGES ON TABLE housings FROM user3;
-- (As user3 - should no longer be able to insert)

-- Cleanup (optional):
-- DROP ROLE test_creator;
-- DROP USER user1;
-- DROP USER user2;
-- DROP USER user3;
-- DROP VIEW v_student_faculty;
-- DROP VIEW v_high_marks;
-- DROP VIEW v_student_marks;
