/* 1 - housings */
CREATE TABLE IF NOT EXISTS housings (
id_housing INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
address VARCHAR
);
SELECT * FROM housings;

/* 2 - faculties */
CREATE TABLE IF NOT EXISTS faculties (
id_faculty INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
id_housing INT,
FOREIGN KEY (id_housing) REFERENCES housings (id_housing)
);
SELECT * FROM faculties;

/* 3 - teachers */
CREATE TABLE IF NOT EXISTS teachers (
id_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
post VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM teachers;

/* 4 - students */
CREATE TABLE IF NOT EXISTS students (
id_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
fio VARCHAR,
contacts VARCHAR,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM students;

/* 5 subjects */
CREATE TABLE IF NOT EXISTS subjects (
id_subject INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR,
learning_hours NUMERIC,
id_faculty INT,
FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty)
);
SELECT * FROM subjects;

/* 6 - marks */
CREATE TABLE IF NOT EXISTS marks (
id_mark INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
mark_type VARCHAR,
id_subject INT,
id_student INT,
mark NUMERIC,
id_teacher INT,
date_m DATE,
id_schedule INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher),
FOREIGN KEY (id_schedule) REFERENCES schedules(id_schedule)
);
SELECT * FROM marks;

/*7 - schedules */
CREATE TABLE IF NOT EXISTS schedules (
    id_schedule INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_faculty INT,
    id_subject INT,
    week_day VARCHAR(20),
    time TIME,
    lesson_type VARCHAR(50),
    id_teacher INT,
    FOREIGN KEY (id_faculty) REFERENCES faculties (id_faculty),
    FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
    FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM schedules;

/*-- Добавление связи с таблицей marks
ALTER TABLE marks ADD COLUMN id_schedule INT;
ALTER TABLE marks ADD FOREIGN KEY (id_schedule) REFERENCES schedules (id_schedule); */

/* 8 - sub_teachers */
CREATE TABLE IF NOT EXISTS sub_teachers (
id_sub_teacher INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_teacher INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_teacher) REFERENCES teachers (id_teacher)
);
SELECT * FROM sub_teachers;

/* 9 - sub_students */
CREATE TABLE IF NOT EXISTS sub_students (
id_sub_student INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
id_subject INT,
id_student INT,
FOREIGN KEY (id_subject) REFERENCES subjects (id_subject),
FOREIGN KEY (id_student) REFERENCES students (id_student)
);
SELECT * FROM sub_students;

-----Добавляем корпуса------
INSERT INTO housings (title, address) VALUES 
('Корпус Радуги', 'ул. Веселая, 10'),
('Арткорпус', 'пр. Художественный, 5'),
('Звуковой Центр', 'ул. Музыкальная, 21'),
('Креативная Башня', 'бул. Архитекторов, 33'),
('Фантазийный Холл', 'пер. Воображения, 7');

SELECT * FROM housings;


----Добавляем направления-----
INSERT INTO faculties (title, id_housing) VALUES 
('Архитектура', 4),
('Изобразительное искусство', 2),
('Музыкальное искусство', 3),
('Цирковое искусство', 5),
('Хореография', 5),
('Кино и мультфильмы', 1),
('Дизайн одежды', 2),
('Театральное искусство', 1),
('Геймдизайн', 4),
('Фантастическая инженерия', 3);

SELECT * FROM faculties;

--ADD teachers---
-- Архитектура (id_faculty=1)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Иванов Петр Сергеевич', '7 (912) 345-67-89', 'Профессор', 1),
('Смирнова Анна Владимировна', 'architect.smirnova@mail.ru', 'Доцент', 1);

-- Изобразительное искусство (id_faculty=2)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Кузнецова Елена Дмитриевна', '7 (923) 456-78-90', 'Профессор', 2),
('Петров Алексей Иванович', 'art.petrov@gmail.com', 'Старший преподаватель', 2),
('Васильева Ольга Николаевна', '7 (934) 567-89-01', 'Доцент', 2);

-- Музыкальное искусство (id_faculty=3)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Соколов Дмитрий Михайлович', 'music.sokolov@yandex.ru', 'Профессор', 3),
('Николаева Татьяна Викторовна', '7 (945) 678-90-12', 'Старший преподаватель', 3);

-- Цирковое искусство (id_faculty=4)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Попов Сергей Александрович', '7 (956) 789-01-23', 'Старший преподаватель', 4),
('Федорова Марина Игоревна', 'circus.fedorova@mail.ru', 'Ассистент', 4);

-- Хореография (id_faculty=5)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Лебедева Анастасия Олеговна', '7 (967) 890-12-34', 'Доцент', 5),
('Козлов Артем Викторович', 'dance.kozlov@gmail.com', 'Старший преподаватель', 5);

-- Кино и мультфильмы (id_faculty=6)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Морозов Игорь Станиславович', 'film.morozov@yandex.ru', 'Профессор', 6),
('Павлова Виктория Сергеевна', '7 (978) 901-23-45', 'Ассистент', 6),
('Сидоров Максим Леонидович', '7 (911) 222-33-44', 'Завуч', 6);

-- Дизайн одежды (id_faculty=7)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Семенова Людмила Анатольевна', 'fashion.semenova@mail.ru', 'Профессор', 7),
('Григорьев Павел Олегович', '7 (989) 012-34-56', 'Доцент', 7);

-- Театральное искусство (id_faculty=8)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Волкова Екатерина Денисовна', 'theatre.volkova@gmail.com', 'Доцент', 8),
('Белов Александр Петрович', '7 (990) 123-45-67', 'Старший преподаватель', 8);

-- Геймдизайн (id_faculty=9)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Тихонов Андрей Владимирович', 'game.tikhonov@yandex.ru', 'Профессор', 9),
('Крылова Юлия Михайловна', '7 (901) 234-56-78', 'Ассистент', 9);

-- Фантастическая инженерия (id_faculty=10)
INSERT INTO teachers (fio, contacts, post, id_faculty) VALUES 
('Орлов Денис Игоревич', 'fantasy.engineer@mail.ru', 'Профессор', 10),
('Зайцева Наталья Валерьевна', '7 (912) 345-67-89', 'Доцент', 10),
('Михайлов Сергей Васильевич', '7 (903) 456-78-90', 'Завуч', 10);



--Добавить Студентов---
-- Архитектура (id_faculty=1)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Соколов Артем Игоревич', '7 (901) 234-56-78', 1),
('Кудабаева Эвита', 'arch.student@mail.ru', 1);

-- Изобразительное искусство (id_faculty=2)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Петрова Виктория Андреевна', 'art.lover@gmail.com', 2),
('Жуков Денис Олегович', '7 (912) 345-67-89', 2);

-- Музыкальное искусство (id_faculty=3)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Никитин Александр Дмитриевич', 'music.prodigy@yandex.ru', 3);

-- Цирковое искусство (id_faculty=4)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Алексеева Марина Валерьевна', '7 (923) 456-78-90', 4);

-- Хореография (id_faculty=5)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Громов Илья Петрович', 'dance.gromov@mail.ru', 5),
('Орлова Дарья Кирилловна', '7 (934) 567-89-01', 5);

-- Кино и мультфильмы (id_faculty=6)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Беляев Максим Андреевич', 'film.director@gmail.com', 6);

-- Дизайн одежды (id_faculty=7)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Степанова Алина Михайловна', 'fashion.design@yandex.ru', 7),
('Фролов Иван Сергеевич', '7 (945) 678-90-12', 7);

-- Театральное искусство (id_faculty=8)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Данилова Ксения Викторовна', 'theatre.star@mail.ru', 8);

-- Геймдизайн (id_faculty=9)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Тимофеев Денис Олегович', 'game.dev@gmail.com', 9),
('Савельева Анна Дмитриевна', '7 (956) 789-01-23', 9);

-- Фантастическая инженерия (id_faculty=10)
INSERT INTO students (fio, contacts, id_faculty) VALUES 
('Кузьмин Павел Андреевич', 'future.engineer@yandex.ru', 10);

SELECT * FROM students;

-- ADD SUBJECTS----
-- Архитектура (id_faculty=1)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('История архитектуры', 120, 1),
('Проектирование зданий', 180, 1),
('Строительные материалы', 90, 1),
('Компьютерное моделирование', 150, 1),
('Ландшафтный дизайн', 110, 1);

-- Изобразительное искусство (id_faculty=2)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Живопись', 160, 2),
('Графика', 120, 2),
('Скульптура', 140, 2),
('История искусств', 100, 2);

-- Музыкальное искусство (id_faculty=3)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Сольфеджио', 150, 3),
('Музыкальная литература', 100, 3),
('Игра на инструменте', 190, 3);

-- Цирковое искусство (id_faculty=4)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Акробатика', 180, 4),
('Жонглирование', 120, 4),
('Клоунада', 90, 4),
('Воздушная гимнастика', 160, 4),
('Эквилибристика', 130, 4);

-- Хореография (id_faculty=5)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Классический танец', 190, 5),
('Современный танец', 150, 5),
('История хореографии', 80, 5),
('Композиция танца', 120, 5);

-- Кино и мультфильмы (id_faculty=6)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Режиссура', 180, 6),
('Операторское мастерство', 140, 6),
('Анимация', 160, 6),
('Сценарное мастерство', 120, 6);

-- Дизайн одежды (id_faculty=7)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Конструирование одежды', 170, 7),
('История моды', 90, 7),
('Текстильный дизайн', 120, 7),
('Технология пошива', 150, 7),
('Модная иллюстрация', 100, 7);

-- Театральное искусство (id_faculty=8)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Актерское мастерство', 190, 8),
('Сценическая речь', 130, 8),
('Сценическое движение', 110, 8),
('История театра', 80, 8);

-- Геймдизайн (id_faculty=9)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Программирование игр', 180, 9),
('3D-моделирование', 160, 9),
('Геймдизайн', 140, 9),
('Концепт-арт', 120, 9);

-- Фантастическая инженерия (id_faculty=10)
INSERT INTO subjects (title, learning_hours, id_faculty) VALUES
('Футуристические технологии', 190, 10),
('Проектирование будущего', 150, 10),
('Нанотехнологии', 130, 10),
('Кибернетика', 140, 10),
('Бионика', 160, 10);

SELECT * FROM subjects;

---ADD SCHEDULE---
SELECT * FROM schedules;
ALTER TABLE schedules ADD COLUMN id_housing INT;

-- Добавим внешний ключ
ALTER TABLE schedules ADD CONSTRAINT fk_schedules_housing 
FOREIGN KEY (id_housing) REFERENCES housings(id_housing);
-- Очищаем таблицу (если нужно)
TRUNCATE TABLE schedules RESTART IDENTITY CASCADE;

-- Вставляем данные с указанием id_housing
INSERT INTO schedules (id_faculty, id_subject, week_day, time, lesson_type, id_teacher, id_housing) VALUES
-- Архитектура (id_housing=4)
(1, 1, 'Понедельник', '09:00', 'Лекция', 1, 4),
(1, 2, 'Понедельник', '11:00', 'Практика', 2, 4),
(1, NULL, 'Вторник', NULL, 'Выходной день', NULL, 4),
(1, 3, 'Среда', '10:00', 'Лекция', 1, 4),
(1, 4, 'Среда', '13:00', 'Практика', 2, 4),
(1, NULL, 'Четверг', NULL, 'Выходной день', NULL, 4),
(1, 5, 'Пятница', '09:00', 'Семинар', 1, 4),
(1, NULL, 'Суббота', NULL, 'Выходной день', NULL, 4),
(1, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 4),

-- Изобразительное искусство (id_housing=2)
(2, NULL, 'Понедельник', NULL, 'Выходной день', NULL, 2),
(2, 6, 'Вторник', '10:00', 'Практика', 3, 2),
(2, 7, 'Вторник', '13:00', 'Лекция', 4, 2),
(2, NULL, 'Среда', NULL, 'Выходной день', NULL, 2),
(2, 8, 'Четверг', '11:00', 'Практика', 5, 2),
(2, 9, 'Четверг', '15:00', 'Семинар', 3, 2),
(2, NULL, 'Пятница', NULL, 'Выходной день', NULL, 2),
(2, NULL, 'Суббота', NULL, 'Выходной день', NULL, 2),
(2, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 2),

-- Музыкальное искусство (id_housing=3)
(3, 10, 'Понедельник', '14:00', 'Практика', 6, 3),
(3, NULL, 'Вторник', NULL, 'Выходной день', NULL, 3),
(3, 11, 'Среда', '10:00', 'Лекция', 7, 3),
(3, NULL, 'Четверг', NULL, 'Выходной день', NULL, 3),
(3, 12, 'Пятница', '11:00', 'Практика', 6, 3),
(3, NULL, 'Суббота', NULL, 'Выходной день', NULL, 3),
(3, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 3),

-- Цирковое искусство (id_housing=5)
(4, NULL, 'Понедельник', NULL, 'Выходной день', NULL, 5),
(4, 13, 'Вторник', '09:00', 'Практика', 8, 5),
(4, 14, 'Вторник', '11:00', 'Практика', 9, 5),
(4, NULL, 'Среда', NULL, 'Выходной день', NULL, 5),
(4, 15, 'Четверг', '10:00', 'Практика', 8, 5),
(4, 16, 'Четверг', '14:00', 'Практика', 9, 5),
(4, 17, 'Пятница', '12:00', 'Семинар', 8, 5),
(4, NULL, 'Суббота', NULL, 'Выходной день', NULL, 5),
(4, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 5),

-- Хореография (id_housing=5)
(5, 18, 'Понедельник', '10:00', 'Практика', 10, 5),
(5, NULL, 'Вторник', NULL, 'Выходной день', NULL, 5),
(5, 19, 'Среда', '11:00', 'Практика', 11, 5),
(5, NULL, 'Четверг', NULL, 'Выходной день', NULL, 5),
(5, 20, 'Пятница', '09:00', 'Лекция', 10, 5),
(5, 21, 'Пятница', '14:00', 'Практика', 11, 5),
(5, NULL, 'Суббота', NULL, 'Выходной день', NULL, 5),
(5, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 5),

-- Кино и мультфильмы (id_housing=1)
(6, NULL, 'Понедельник', NULL, 'Выходной день', NULL, 1),
(6, 22, 'Вторник', '10:00', 'Лекция', 12, 1),
(6, 23, 'Вторник', '13:00', 'Практика', 13, 1),
(6, NULL, 'Среда', NULL, 'Выходной день', NULL, 1),
(6, 24, 'Четверг', '11:00', 'Практика', 14, 1),
(6, 25, 'Четверг', '15:00', 'Семинар', 12, 1),
(6, NULL, 'Пятница', NULL, 'Выходной день', NULL, 1),
(6, NULL, 'Суббота', NULL, 'Выходной день', NULL, 1),
(6, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 1),

-- Дизайн одежды (id_housing=2)
(7, 26, 'Понедельник', '09:00', 'Лекция', 15, 2),
(7, 27, 'Понедельник', '11:00', 'Практика', 16, 2),
(7, NULL, 'Вторник', NULL, 'Выходной день', NULL, 2),
(7, 28, 'Среда', '10:00', 'Практика', 15, 2),
(7, 29, 'Среда', '14:00', 'Практика', 16, 2),
(7, 30, 'Пятница', '12:00', 'Семинар', 15, 2),
(7, NULL, 'Суббота', NULL, 'Выходной день', NULL, 2),
(7, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 2),

-- Театральное искусство (id_housing=1)
(8, NULL, 'Понедельник', NULL, 'Выходной день', NULL, 1),
(8, 31, 'Вторник', '10:00', 'Практика', 17, 1),
(8, 32, 'Вторник', '13:00', 'Лекция', 18, 1),
(8, NULL, 'Среда', NULL, 'Выходной день', NULL, 1),
(8, 33, 'Четверг', '11:00', 'Практика', 17, 1),
(8, 34, 'Четверг', '15:00', 'Практика', 18, 1),
(8, NULL, 'Пятница', NULL, 'Выходной день', NULL, 1),
(8, NULL, 'Суббота', NULL, 'Выходной день', NULL, 1),
(8, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 1),

-- Геймдизайн (id_housing=4)
(9, 35, 'Понедельник', '14:00', 'Лекция', 19, 4),
(9, NULL, 'Вторник', NULL, 'Выходной день', NULL, 4),
(9, 36, 'Среда', '10:00', 'Практика', 20, 4),
(9, 37, 'Среда', '13:00', 'Практика', 19, 4),
(9, NULL, 'Четверг', NULL, 'Выходной день', NULL, 4),
(9, 38, 'Пятница', '11:00', 'Семинар', 20, 4),
(9, NULL, 'Суббота', NULL, 'Выходной день', NULL, 4),
(9, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 4),

-- Фантастическая инженерия (id_housing=3)
(10, NULL, 'Понедельник', NULL, 'Выходной день', NULL, 3),
(10, 39, 'Вторник', '09:00', 'Лекция', 21, 3),
(10, 40, 'Вторник', '11:00', 'Практика', 22, 3),
(10, NULL, 'Среда', NULL, 'Выходной день', NULL, 3),
(10, 41, 'Четверг', '10:00', 'Практика', 23, 3),
(10, 42, 'Четверг', '14:00', 'Семинар', 21, 3),
(10, 43, 'Пятница', '12:00', 'Практика', 22, 3),
(10, NULL, 'Суббота', NULL, 'Выходной день', NULL, 3),
(10, NULL, 'Воскресенье', NULL, 'Выходной день', NULL, 3);

-- Проверяем, что все записи имеют правильный id_housing
/*
SELECT 
    s.id_schedule,
    f.title AS faculty,
    h.title AS housing,
    s.id_housing,
    CASE 
        WHEN s.id_housing = f.id_housing THEN 'OK'
        ELSE 'ERROR'
    END AS status
FROM schedules s
JOIN faculties f ON s.id_faculty = f.id_faculty
JOIN housings h ON f.id_housing = h.id_housing
ORDER BY s.id_schedule; */




SELECT * FROM students;
SELECT * FROM schedules;
 --TRUNCATE TABLE schedules;
 TRUNCATE TABLE schedules RESTART IDENTITY CASCADE;
 TRUNCATE TABLE schedules RESTART IDENTITY;
---TRUNCATE TABLE marks;
SELECT * FROM schedules;
--SELECT * FROM marks;

--ADD MARKS---

-- Очищаем таблицу marks и сбрасываем счетчик ID
TRUNCATE TABLE marks RESTART IDENTITY;

-- Добавляем оценки для всех студентов (15 студентов, 15% = ~2 студента с "НА")

-- Студент Кудабаева Эвита (id_student=2) - все пятерки
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 1, 2, 5, 1, '2023-12-15', 1),
('Экзамен', 2, 2, 5, 2, '2023-12-16', 2),
('Зачет', 3, 2, 5, 1, '2023-12-17', 4),
('Экзамен', 4, 2, 5, 2, '2023-12-18', 5),
('Зачет', 5, 2, 5, 1, '2023-12-19', 7);

-- Соколов Артем Игоревич (id_student=1)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 1, 1, 4, 1, '2023-12-15', 1),
('Зачет', 2, 1, 5, 2, '2023-12-16', 2),
('Экзамен', 3, 1, 3, 1, '2023-12-17', 4);

-- Петрова Виктория Андреевна (id_student=3)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 6, 3, 5, 3, '2023-12-15', 19),
('Зачет', 7, 3, 4, 4, '2023-12-16', 20),
('Экзамен', 8, 3, 5, 5, '2023-12-17', 23);

-- Жуков Денис Олегович (id_student=4) - один из 15% с "НА"
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('НА', 6, 4, 2, 3, '2023-12-15', 19),  -- Не аттестован
('Зачет', 9, 4, 4, 3, '2023-12-16', 24);

-- Никитин Александр Дмитриевич (id_student=5)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 10, 5, 4, 6, '2023-12-15', 28),
('Зачет', 11, 5, 5, 7, '2023-12-16', 31),
('Экзамен', 12, 5, 4, 6, '2023-12-17', 34);

-- Алексеева Марина Валерьевна (id_student=6)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 13, 6, 5, 8, '2023-12-15', 37),
('Зачет', 14, 6, 4, 9, '2023-12-16', 38),
('Экзамен', 15, 6, 5, 8, '2023-12-17', 41);

-- Громов Илья Петрович (id_student=7)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 18, 7, 4, 10, '2023-12-15', 46),
('Зачет', 19, 7, 5, 11, '2023-12-16', 49);

-- Орлова Дарья Кирилловна (id_student=8)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 18, 8, 5, 10, '2023-12-15', 46),
('Зачет', 20, 8, 4, 10, '2023-12-16', 50),
('Экзамен', 21, 8, 5, 11, '2023-12-17', 51);

-- Беляев Максим Андреевич (id_student=9)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 22, 9, 4, 12, '2023-12-15', 55),
('Зачет', 23, 9, 5, 13, '2023-12-16', 56);

-- Степанова Алина Михайловна (id_student=10)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 26, 10, 5, 15, '2023-12-15', 64),
('Зачет', 27, 10, 4, 16, '2023-12-16', 65),
('Экзамен', 28, 10, 5, 15, '2023-12-17', 67);

-- Фролов Иван Сергеевич (id_student=11) - один из 15% с "НА"
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('НА', 26, 11, 2, 15, '2023-12-15', 64),  -- Не аттестован
('Зачет', 30, 11, 4, 15, '2023-12-16', 69);

-- Данилова Ксения Викторовна (id_student=12)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 31, 12, 5, 17, '2023-12-15', 73),
('Зачет', 32, 12, 5, 18, '2023-12-16', 74),
('Экзамен', 33, 12, 5, 17, '2023-12-17', 76);

-- Тимофеев Денис Олегович (id_student=13)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 35, 13, 4, 19, '2023-12-15', 82),
('Зачет', 36, 13, 5, 20, '2023-12-16', 84);

SELECT * FROM marks;

-- Савельева Анна Дмитриевна (id_student=14)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 35, 14, 5, 19, '2023-12-15', 82);
SELECT * FROM schedules;
-- Кузьмин Павел Андреевич (id_student=15)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 39, 15, 5, 21, '2023-12-15', 82),  -- Исправлено id_schedule=82 вместо 91
('Зачет', 40, 15, 5, 22, '2023-12-16', 84),    -- Исправлено id_schedule=84 вместо 92
('Экзамен', 42, 15, 5, 21, '2023-12-17', 85);  -- Исправлено id_schedule=85 вместо 95

-- Оценки для всех преподавателей (используем только существующие id_schedule)
INSERT INTO marks (mark_type, id_subject, id_student, mark, id_teacher, date_m, id_schedule) VALUES
('Экзамен', 24, 9, 5, 14, '2023-12-18', 58),
('Экзамен', 41, 15, 4, 23, '2023-12-18', 82);  -- Исправлено id_schedule=82 вместо 94

SELECT * FROM marks;

--ADD SUB_STUDENTS---
-- Очищаем таблицу sub_students и сбрасываем счетчик ID
TRUNCATE TABLE sub_students RESTART IDENTITY;

-- Добавляем записи, проверяя соответствие id_student и id_subject

-- Архитектура (id_faculty=1)
-- Соколов Артем Игоревич (id_student=1)
INSERT INTO sub_students (id_subject, id_student) VALUES
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1);

-- Кудабаева Эвита (id_student=2)
INSERT INTO sub_students (id_subject, id_student) VALUES
(1, 2), (2, 2), (3, 2), (4, 2), (5, 2);

-- Изобразительное искусство (id_faculty=2)
-- Петрова Виктория Андреевна (id_student=3)
INSERT INTO sub_students (id_subject, id_student) VALUES
(6, 3), (7, 3), (8, 3), (9, 3);

-- Жуков Денис Олегович (id_student=4)
INSERT INTO sub_students (id_subject, id_student) VALUES
(6, 4), (7, 4), (8, 4), (9, 4);

-- Музыкальное искусство (id_faculty=3)
-- Никитин Александр Дмитриевич (id_student=5)
INSERT INTO sub_students (id_subject, id_student) VALUES
(10, 5), (11, 5), (12, 5);

-- Цирковое искусство (id_faculty=4)
-- Алексеева Марина Валерьевна (id_student=6)
INSERT INTO sub_students (id_subject, id_student) VALUES
(13, 6), (14, 6), (15, 6), (16, 6), (17, 6);

-- Хореография (id_faculty=5)
-- Громов Илья Петрович (id_student=7)
INSERT INTO sub_students (id_subject, id_student) VALUES
(18, 7), (19, 7), (20, 7), (21, 7);

-- Орлова Дарья Кирилловна (id_student=8)
INSERT INTO sub_students (id_subject, id_student) VALUES
(18, 8), (19, 8), (20, 8), (21, 8);

-- Кино и мультфильмы (id_faculty=6)
-- Беляев Максим Андреевич (id_student=9)
INSERT INTO sub_students (id_subject, id_student) VALUES
(22, 9), (23, 9), (24, 9), (25, 9);

-- Дизайн одежды (id_faculty=7)
-- Степанова Алина Михайловна (id_student=10)
INSERT INTO sub_students (id_subject, id_student) VALUES
(26, 10), (27, 10), (28, 10), (29, 10), (30, 10);

-- Фролов Иван Сергеевич (id_student=11)
INSERT INTO sub_students (id_subject, id_student) VALUES
(26, 11), (27, 11), (28, 11), (29, 11), (30, 11);

-- Театральное искусство (id_faculty=8)
-- Данилова Ксения Викторовна (id_student=12)
INSERT INTO sub_students (id_subject, id_student) VALUES
(31, 12), (32, 12), (33, 12), (34, 12);

-- Геймдизайн (id_faculty=9)
-- Тимофеев Денис Олегович (id_student=13)
INSERT INTO sub_students (id_subject, id_student) VALUES
(35, 13), (36, 13), (37, 13), (38, 13);

-- Савельева Анна Дмитриевна (id_student=14)
INSERT INTO sub_students (id_subject, id_student) VALUES
(35, 14), (36, 14), (37, 14), (38, 14);

-- Фантастическая инженерия (id_faculty=10)
-- Кузьмин Павел Андреевич (id_student=15)
INSERT INTO sub_students (id_subject, id_student) VALUES
(39, 15), (40, 15), (41, 15), (42, 15), (43, 15);

SELECT * FROM sub_students;



--ДОБАВИТЬ САБ-ТИЧЕРС--
-- Очищаем таблицу sub_teachers и сбрасываем счетчик ID
TRUNCATE TABLE sub_teachers RESTART IDENTITY;

-- Добавляем записи, проверяя соответствие id_teacher и id_subject

-- Архитектура (id_faculty=1)
-- Иванов Петр Сергеевич (id_teacher=1) преподает предметы 1,3,5
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(1, 1), (3, 1), (5, 1);

-- Смирнова Анна Владимировна (id_teacher=2) преподает предметы 2,4
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(2, 2), (4, 2);

-- Изобразительное искусство (id_faculty=2)
-- Кузнецова Елена Дмитриевна (id_teacher=3) преподает предметы 6,9
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(6, 3), (9, 3);

-- Петров Алексей Иванович (id_teacher=4) преподает предмет 7
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(7, 4);

-- Васильева Ольга Николаевна (id_teacher=5) преподает предмет 8
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(8, 5);

-- Музыкальное искусство (id_faculty=3)
-- Соколов Дмитрий Михайлович (id_teacher=6) преподает предметы 10,12
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(10, 6), (12, 6);

-- Николаева Татьяна Викторовна (id_teacher=7) преподает предмет 11
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(11, 7);

-- Цирковое искусство (id_faculty=4)
-- Попов Сергей Александрович (id_teacher=8) преподает предметы 13,15,17
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(13, 8), (15, 8), (17, 8);

-- Федорова Марина Игоревна (id_teacher=9) преподает предметы 14,16
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(14, 9), (16, 9);

-- Хореография (id_faculty=5)
-- Лебедева Анастасия Олеговна (id_teacher=10) преподает предметы 18,20
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(18, 10), (20, 10);

-- Козлов Артем Викторович (id_teacher=11) преподает предметы 19,21
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(19, 11), (21, 11);

-- Кино и мультфильмы (id_faculty=6)
-- Морозов Игорь Станиславович (id_teacher=12) преподает предметы 22,25
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(22, 12), (25, 12);

-- Павлова Виктория Сергеевна (id_teacher=13) преподает предмет 23
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(23, 13);

-- Сидоров Максим Леонидович (id_teacher=14) преподает предмет 24
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(24, 14);

-- Дизайн одежды (id_faculty=7)
-- Семенова Людмила Анатольевна (id_teacher=15) преподает предметы 26,28,30
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(26, 15), (28, 15), (30, 15);

-- Григорьев Павел Олегович (id_teacher=16) преподает предметы 27,29
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(27, 16), (29, 16);

-- Театральное искусство (id_faculty=8)
-- Волкова Екатерина Денисовна (id_teacher=17) преподает предметы 31,33
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(31, 17), (33, 17);

-- Белов Александр Петрович (id_teacher=18) преподает предметы 32,34
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(32, 18), (34, 18);

-- Геймдизайн (id_faculty=9)
-- Тихонов Андрей Владимирович (id_teacher=19) преподает предметы 35,37
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(35, 19), (37, 19);

-- Крылова Юлия Михайловна (id_teacher=20) преподает предметы 36,38
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(36, 20), (38, 20);

-- Фантастическая инженерия (id_faculty=10)
-- Орлов Денис Игоревич (id_teacher=21) преподает предметы 39,42
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(39, 21), (42, 21);

-- Зайцева Наталья Валерьевна (id_teacher=22) преподает предметы 40,43
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(40, 22), (43, 22);

-- Михайлов Сергей Васильевич (id_teacher=23) преподает предмет 41
INSERT INTO sub_teachers (id_subject, id_teacher) VALUES
(41, 23);

SELECT * FROM sub_teachers;

--CALLS--
SELECT * FROM housings;
SELECT * FROM faculties;
SELECT * FROM students;
SELECT * FROM teachers;
SELECT * FROM subjects;
SELECT * FROM schedules;
SELECT * FROM marks;
SELECT * FROM sub_students;
SELECT * FROM sub_teachers;



-------main part finished-----

